### ISSUE TITLE
flatcam-beta: Cutout crashes

### ISSUE THREAD

**Issue by kilometers** [tomoyanonymous/homebrew-flatcam#28]
Hi there, I realize this isn't the original developer / repo of flatcam and its subsequent versions, however I'm wondering if others in this corner of the FlatCAM community have encountered this issue.

Expected behavior:
Click on "Cutout Tool" for a .gtl gerber file, and configure a board cutout

Actual behavior:
FlatCAM immediately crashes when "Cutout Tool" is clicked, giving the following terminal output:

```
[DEBUG][Dummy-8] parseGerber.Gerber.bounds()
WARNING: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appTools/ToolCutOut.py", line 154, in run
    self.set_tool_ui()
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appTools/ToolCutOut.py", line 246, in set_tool_ui
    self.on_tool_add(custom_dia=tool_dia)
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appTools/ToolCutOut.py", line 358, in on_tool_add
    self.on_tool_default_add()
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appTools/ToolCutOut.py", line 454, in on_tool_default_add
    self.update_ui(self.default_data)
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appTools/ToolCutOut.py", line 263, in update_ui
    self.ui.mpass_cb.set_value(float(tool_dict["tools_cutout_mdepth"]))
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appGUI/GUIElements.py", line 1520, in set_value
    self.setChecked(val)
TypeError: setChecked(self, a0: bool): argument 1 has unexpected type 'float'
zsh: abort      flatcam
(base) milesbaird@Miless-MacBook-Pro ~ % /opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 12 leaked semaphore objects to clean up at shutdown
```

I'm on Apple M2, Sonoma 14.5

There seems to be a type mismatch in the code. Thoughts?

**Comment by kilometers** [comment]
Eventually I got flatcam-evo working, and that bypasses the crash. I'm assuming there's not much knowledge about the problem with -beta, so just closing this.
