### ISSUE TITLE
error cloning flatcam under OSX 13.6.3

### ISSUE THREAD

**Issue by kokospalme** [tomoyanonymous/homebrew-flatcam#31]
I'm having a hard time installing flatcam on OSX. When trying to install the software with ```brew install flatcam``` I'm getting the following error:
```
==> Cloning https://bitbucket.org/jpcgt/flatcam.git
Cloning into '/Users/****/Library/Caches/Homebrew/flatcam--git'...
==> Checking out revision 46454c293a9b390c931b52eb6217ca47e13b0231
HEAD is now at 46454c29 Merged in marius_stanciu/flatcam_mpl/Fix_for_Flip_Rotate_Skew_pull_request (pull request #113)
==> Installing flatcam from tomoyanonymous/flatcam
==> Installing dependencies for tomoyanonymous/flatcam/flatcam: cartr/qt4/openssl@1.0, cartr/qt4/qt@4, cartr/qt4/qt-webkit@2.3, ca-certificates, sip, cartr/qt4/pyqt@4, cmake, certifi, sphinx-doc, cartr/qt4/shiboken@1.2, cartr/qt4/pyside@1.2, gcc, pkgconf, libtommath, tcl-tk and python-tk@3.13
==> Installing tomoyanonymous/flatcam/flatcam dependency: cartr/qt4/openssl@1.0
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2t --openssldir=/opt/ho
==> make depend
==> make
Last 15 lines from /Users/***/Library/Logs/Homebrew/openssl@1.0/03.make:
 ^
x86_64cpuid.s:273:10: error: unknown token in expression
 cmpq $0,%rax
         ^
x86_64cpuid.s:273:10: error: invalid operand
 cmpq $0,%rax
         ^
x86_64cpuid.s:274:9: error: unknown token in expression
 cmoveq %rcx,%rax
        ^
x86_64cpuid.s:274:9: error: invalid operand
 cmoveq %rcx,%rax
        ^
make[1]: *** [x86_64cpuid.o] Error 1
make: *** [build_crypto] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/cartr/homebrew-qt4/issues

```

What could be the problem here?

**Comment by tomoyanonymous** [comment]
Normal `flatcam` is quite old now. Try  `flatcam-beta‘ or `flatcam-evo` first.

**Comment by kokospalme** [comment]
installing flatcam-beta and then starting ```flatcam``` results in this:
```
==> Running `brew cleanup flatcam-beta`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
chris@Christophers-MacBook-Pro ~ % flatcam

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/homebrew/bin/flatcam", line 7, in <module>
    from app_Main import App
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/app_Main.py", line 47, in <module>
    from appCommon.Common import LoudDict
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appCommon/Common.py", line 18, in <module>
    from appGUI.VisPyVisuals import ShapeCollection
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appGUI/VisPyVisuals.py", line 9, in <module>
    from vispy.visuals import CompoundVisual, LineVisual, MeshVisual, TextVisual, MarkersVisual
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/__init__.py", line 14, in <module>
    from .axis import AxisVisual  # noqa
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/axis.py", line 13, in <module>
    from .text import TextVisual
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/text/__init__.py", line 7, in <module>
    from .text import TextVisual  # noqa
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/text/text.py", line 18, in <module>
    from ._sdf_cpu import _calc_distance_field
Traceback (most recent call last):
  File "/opt/homebrew/bin/flatcam", line 7, in <module>
    from app_Main import App
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/app_Main.py", line 47, in <module>
    from appCommon.Common import LoudDict
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appCommon/Common.py", line 18, in <module>
    from appGUI.VisPyVisuals import ShapeCollection
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/appGUI/VisPyVisuals.py", line 9, in <module>
    from vispy.visuals import CompoundVisual, LineVisual, MeshVisual, TextVisual, MarkersVisual
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/__init__.py", line 14, in <module>
    from .axis import AxisVisual  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/axis.py", line 13, in <module>
    from .text import TextVisual
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/text/__init__.py", line 7, in <module>
    from .text import TextVisual  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/flatcam-beta/8.9.94/libexec/lib/python3.11/site-packages/vispy/visuals/text/text.py", line 18, in <module>
    from ._sdf_cpu import _calc_distance_field
  File "vispy/visuals/text/_sdf_cpu.pyx", line 1, in init vispy.visuals.text._sdf_cpu
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

flatcam-evo does also not work... Is there no version that is a standard setup or application file? Or could this not be compiled as one?

**Comment by tomoyanonymous** [comment]
> Is there no version that is a standard setup or application file? Or could this not be compiled as one?

Actually, yes because the initial author stopped developing and there are no official core maintainer for these 5 years.

I think today's most actively maintained version is Flatcam Evo by Marius Stanciu, so I'm going to keep only flatcam-evo in this tap in the near future.

https://bitbucket.org/marius_stanciu/flatcam_beta/commits/branch/Beta_8.995

Also because flatcam is just a python application, many things depend on user's environments. We can pack the application to .app using something like pyinstaller but anyway it is hard to maintain the distribution of .app bundle because of codesigning & etc. That is perhaps why the maintainers care only for Windows.

BTW, I'll take a look of the latest version later.

It looks that the `requirements.txt` requires `numpy>=1.16` but it should not be 2.x as the error message indicates.
Maybe it works by replacing it to `numpy>=1.16, < 2.0` by applying a patch like this line

https://github.com/tomoyanonymous/homebrew-flatcam/blob/0b03b0021b44231440157d4ee904f92c2085b8bc/flatcam-beta.rb#L19

If you can test, try to open PR.

**Comment by kokospalme** [comment]
Thank you for your quick support, that worked for me :)
