### ISSUE TITLE
ModuleNotFoundError on numpy.core._multiarray_umath

### ISSUE THREAD

**Issue by ryanbarry** [tomoyanonymous/homebrew-flatcam#7]
i'm on mojave 10.14.4, and was able to install (despite an issue building the dependency [cartr/qt4/pyside@1.2](https://github.com/cartr/homebrew-qt4/issues/66)) but then when trying to run, got the following error:
```bash
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/usr/local/bin/flatcam", line 13, in <module>
    from FlatCAMApp import App
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/FlatCAMApp.py", line 30, in <module>
    import ObjectCollection
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/ObjectCollection.py", line 9, in <module>
    from FlatCAMObj import *
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/FlatCAMObj.py", line 15, in <module>
    from camlib import *
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/camlib.py", line 16, in <module>
    from matplotlib.figure import Figure
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/matplotlib/figure.py", line 21, in <module>
    from matplotlib import backends, docstring
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 9, in <module>
    from matplotlib.backend_bases import _Backend
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/matplotlib/textpath.py", line 8, in <module>
    from matplotlib import cbook, dviread, font_manager, rcParams
  File "/usr/local/Cellar/flatcam/8.5.0/libexec/lib/python3.7/site-packages/matplotlib/font_manager.py", line 48, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: numpy.core.multiarray failed to import
```

following instructions found on a [stackoverflow post of a similar error](https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import), i did `/usr/local/Cellar/flatcam/8.5.0/libexec/bin/pip install -U numpy` which updated it to `numpy-1.16.4`.

it seems to have worked (flatcam starts successfully) but i wanted to report back to see if i could offer a PR to update the dependency or if there would be another suggested fix.

**Comment by tomoyanonymous** [comment]
Thanks for reporting.

I updated python dependencies. 668dc46c584f6d619f8fbecd92d293c018a9b6ec

And there's no build/runtime error except for the [pyside1.2 build error](https://github.com/cartr/homebrew-qt4/issues/66). 
I skipped the installation by choosing "ignore" in --debug option as in readme and it seems to be no problem.
Please try it!
